### ISSUE TITLE
[Balancing] Early game difficulty is a bit punishing

### ISSUE THREAD

**Issue by Fough** [shirogames/northgard#15]
This is partly related to issue #9 ([Balancing] Wolves may be a bit beefy during early-game) but in a more general way, I felt that early game was a little bit punishing and forced me to relaunch the game until I met more favorable conditions.
Now, I'm by no way a great player for strategy/management games, but since I played only with the Heidrun clan which, if I'm guessing right, the "easy" mode, I feel that the game might a bit hard to pick up.

Under most conditions, I had trouble making the right choices and not die of starvation during the first winter. Of course, the current lack of tutorialization may be at fault here, but if a comprehensive tutorial is not planned, please consider giving a little more starting resources to the player. Issue #13 ([Readability] Deers look like (and could be) a game mechanic) could play this role.

**Comment by ncannasse** [comment]
We will have a tutorial/campaign and rebalance the game difficulty accordingly

**Comment by Fough** [comment]
Okay, closing to postpone.
