### ISSUE TITLE
[GUI] It's hard to tell how advanced is each "player" in the Fame race

### ISSUE THREAD

**Issue by Fough** [shirogames/northgard#16]
I understand that the Fame race will be tutorialized, but for the context, the first time I lost (one opponent became King of Northgard), I was not aware that he was even close to doing so (let alone knowing this was the victory condition).

So once I did get that, I regretted the race was represented only with figures, and no visual "timeline-like" chart, with milestones representing each Fame rank. This way, it would be much easier to tell how advanced one is in the race, and how close to winning the first one is.

**Comment by ncannasse** [comment]
We have that in the next update (button with "Victory Conditions") :)
